### ISSUE TITLE
Fabric 1.18.1 - Crash rendering entity in world

### ISSUE THREAD

**Issue by bessiq** [CyborgCabbage/OopsAllArmor#2]
Hi there!

Love the mod! Unfortunately, I've discovered an issue with it when also using the Cosmetic Armor + Trinkets mods. Essentially, when trying to place ANY equipment into a cosmetic slot, the game crashes. And not just your mod's stuff, but vanilla and other mods' equipment.

I initially discovered the issue when trying to place some glasses from the Observed mod into the cosmetic head slot, but then disabled mods in groups to narrow down the issue. When I was doing this, I usually tested with the vanilla leather cap, or sometimes other vanilla helmets - all caused the game to crash. I also tried another slot - an iron chestplate in the Cosmetic Armor chest slot, and the game crashed also.

Here's the crash report: [crash-2022-01-01_13.00.43-client.txt](https://github.com/CyborgCabbage/OopsAllArmor/files/7798051/crash-2022-01-01_13.00.43-client.txt)
And here's the issue I created on the Trinkets repo if their response is helpful: emilyploszaj/trinkets#140

Let me know if you need any other info!

**Comment by CyborgCabbage** [comment]
Thank you for submitting a bug report, I have published a fix for this as version 1.1.2
It should be available as soon as CurseForge approve it (a couple days at most).
